### ISSUE TITLE
Killing a BST mob, won't despawn pet

### ISSUE THREAD

**Issue by Gradius2** [topaz-next/topaz#2667] opened 2021-02-28 05:02 UTC
- [X] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [X] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [X] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by Gradius2** [comment] 2021-02-28 05:11
Killing BST mobs faster, the pet shouldn't despawn too?  I remember they do in official ffxi, well, at least around 2012 release (last time I played on official).

![img_20210228_020828](https://user-images.githubusercontent.com/11011463/109408630-027a5d00-796a-11eb-8bf9-fda69d647db4.jpg)

**Comment by Gradius2** [comment] 2021-02-28 05:27
Can get the error with other mobs too:
[28/Feb] [02:25:18] [Action Info] CLIENT Gradius PERFORMING ACTION 03
[28/Feb] [02:25:21] [Error] luautils::onMobDeath (./scripts/zones/Lower_Delkfutts_Tower/mobs/Gigass_Bat.lua): **undefined procedure onMobDeath**
[28/Feb] [02:26:41] [Info] parse: 01A | 10BA 10B9 0E from user: Gradius

**Comment by Gradius2** [comment] 2021-02-28 06:44
Hmm, this was already mentioned before (forget it).

I'm closing this one.

**Comment by ShiyoKozuki** [comment] 2021-02-28 06:51
This is accurate, only elementals from summoner mobs should despawn.

**Comment by ghost** [comment] 2021-02-28 20:54
Closing this issue, Mob BST pets do not despawn on retail on their master being defeated.  This is not a bug.

**Closed as completed by ghost** 2021-02-28 20:54 UTC
