### ISSUE TITLE
Treasure hunter is incorrect

### ISSUE THREAD

**Issue by ShiyoKozuki** [topaz-next/topaz#2378] opened 2021-01-06 07:49 UTC
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Information on how TH actually works was officially released by SE in 2020.
https://www.bg-wiki.com/bg/Treasure_Hunter_II

The below code is wrong, and makes TH too powerful. The table above shows how it's supposed to work.

Basically, the mob_droplist.sql item rate needs to be changed to have "rarities" -
100% Guaranteed 1
24% Very common 2
15% Common 3
10% Uncommon 4
5% Rare 5
1% Very Rare 6
0.5% Ultra rare 7

Instead of percentages for every item, look at every item via http://www.ffxidb.com/ and determine where the best fit for every item is. Then assign a number to every drop type(as shown above) and use that instead. This will make creating mob drops more efficient and easier(as well as accurate).

As to coding how TH functions...I have no idea.  I do not know enough about coding to propose an idea for that.  However, the table on bg wiki(official table from SE) gives all the data you'd need to create such code.

```
void CMobEntity::DropItems(CCharEntity* PChar)
{
    //Adds an item to the treasure pool and returns true if the pool has been filled
    auto AddItemToPool = [this, PChar](uint16 ItemID, uint8 dropCount)
    {
        PChar->PTreasurePool->AddItem(ItemID, this);
        return dropCount >= TREASUREPOOL_SIZE;
    };

    //Limit number of items that can drop to the treasure pool size
    uint8 dropCount = 0;

    DropList_t* DropList = itemutils::GetDropList(m_DropID);
    //ShowDebug(CL_CYAN"DropID: %u dropping with TH Level: %u\n" CL_RESET, PMob->m_DropID, PMob->m_THLvl);

    if (DropList != nullptr && !getMobMod(MOBMOD_NO_DROPS) && (DropList->Items.size() || DropList->Groups.size()))
    {
        //THLvl is the number of 'extra chances' at an item. If the item is obtained, then break out.
        int16 maxRolls = 1 + (m_THLvl > 2 ? 2 : m_THLvl);
        int16 bonus = (m_THLvl > 2 ? (m_THLvl - 2) * 10 : 0);

        for (const DropGroup_t& group : DropList->Groups)
        {
            for (int16 roll = 0; roll < maxRolls; ++roll)
            {
                //Determine if this group should drop an item
                if (group.GroupRate > 0 && tpzrand::GetRandomNumber(1000) < group.GroupRate * map_config.drop_rate_multiplier + bonus)
                {
                    //Each item in the group is given its own weight range which is the previous value to the previous value + item.DropRate
                    //Such as 2 items with drop rates of 200 and 800 would be 0-199 and 200-999 respectively
                    uint16 previousRateValue = 0;
                    uint16 itemRoll = tpzrand::GetRandomNumber(1000);
                    for (const DropItem_t& item : group.Items)
                    {
                        if (previousRateValue + item.DropRate > itemRoll)
                        {
                            if (AddItemToPool(item.ItemID, ++dropCount))
                                return;
                            break;
                        }
                        previousRateValue += item.DropRate;
                    }
                    break;
                }
            }
        }

        for (const DropItem_t& item : DropList->Items)
        {
            for (int16 roll = 0; roll < maxRolls; ++roll)
            {
                if (item.DropRate > 0 && tpzrand::GetRandomNumber(1000) < item.DropRate * map_config.drop_rate_multiplier + bonus)
                {
                    if (AddItemToPool(item.ItemID, ++dropCount))
                        return;
                    break;
                }
            }
        }
    }


```

**Comment by zach2good** [comment] 2021-01-06 08:24
https://github.com/topaz-next/topaz/issues?q=is%3Aissue+is%3Aopen+treasure+hunter

Duplicate of: https://github.com/topaz-next/topaz/issues/1348

**Closed as completed by zach2good** 2021-01-06 08:24 UTC
